export const GET_ALL_PROGRAMS_SUCCESS = "GET_ALL_PROGRAMS_SUCCESS";
export const GET_ALL_PROGRAMS_REJECTED = "GET_ALL_PROGRAMS_REJECTED";
export const GET_ALL_PROGRAMS_PENDING = "GET_ALL_PROGRAMS_PENDING";

export const GET_PROGRAM_BY_ID_PENDING = "GET_PROGRAM_BY_ID_PENDING";
export const GET_PROGRAM_BY_ID_REJECTED = "GET_PROGRAM_BY_ID_REJECTED";
export const GET_PROGRAM_BY_ID_SUCCESS = "GET_PROGRAM_BY_ID_SUCCESS";

export const ADD_PROGRAM_SUCCESS = "ADD_PROGRAM_SUCCESS";
export const ADD_PROGRAM_REJECTED = "ADD_PROGRAM_REJECTED";
export const ADD_PROGRAM_PENDING = "ADD_PROGRAM_PENDING";

export const EDIT_PROGRAM_SUCCESS = "EDIT_PROGRAM_SUCCESS";
export const EDIT_PROGRAM_REJECTED = "EDIT_PROGRAM_REJECTED";
export const EDIT_PROGRAM_PENDING = "EDIT_PROGRAM_PENDING";

export const DELETE_PROGRAM_SUCCESS = "DELETE_PROGRAM_SUCCESS";
export const DELETE_PROGRAM_REJECTED = "DELETE_PROGRAM_REJECTED";
export const DELETE_PROGRAM_PENDING = "DELETE_PROGRAM_PENDING";
